services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: churn
      POSTGRES_USER: churn_user
      POSTGRES_PASSWORD: churn_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U churn_user -d churn"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
